# This configuration was influenced by googletest:
# https://github.com/google/googletest/blob/master/appveyor.yml

environment:
  matrix:
    - ARCH: x86
      GENERATOR: Visual Studio 14 2015
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - ARCH: x86_64
      GENERATOR: Visual Studio 14 2015 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - ARCH: x86
      GENERATOR: Visual Studio 15 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - ARCH: x86_64
      GENERATOR: Visual Studio 15 2017 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

configuration:
  - Debug
  - Release

# Unclear how to do this in PowerShell.
install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user
  - conan --version
  - conan remote add autocheck https://api.bintray.com/conan/thejohnfreeman/autocheck
  - conan remote list

# `/m` is for parallel build.
build_script:
  - ps: |
      md build
      cd build
      conan install `
        --setting "arch=$env:ARCH" `
        --setting "build_type=$env:CONFIGURATION" `
        ..
      cmake `
        -G "$env:GENERATOR" `
        "-DCMAKE_CONFIGURATION_TYPES=Debug;Release" `
        ..
      if ($LastExitCode -ne 0) {
        throw $ErrorMessage
      }
      cmake --build . --config "$env:CONFIGURATION" -- /m
      if ($LastExitCode -ne 0) {
        throw $ErrorMessage
      }

test_script:
  - ps: |
      ctest -C "$env:CONFIGURATION" -V
      if ($LastExitCode -ne 0) {
        throw $ErrorMessage
      }
