sudo: required
language: cpp

addons:
  apt:
    packages:
      - g++-7

matrix:
  include:
    # We need to use Ubuntu Xenial to upgrade pip.
    - os: linux
      dist: xenial
      compiler: clang
      env:
        - BUILD_TYPE=Debug
        - CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'
        - LIBCXX=libstdc++11
    - os: linux
      dist: xenial
      compiler: clang
      env:
        - BUILD_TYPE=Release
        - CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'
        - LIBCXX=libstdc++11
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
        - CC=gcc-7
        - CXX=g++-7
        - CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'
        - LIBCXX=libstdc++11
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        - BUILD_TYPE=Release
        - CC=gcc-7
        - CXX=g++-7
        - CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'
        - LIBCXX=libstdc++11
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Debug
        - LIBCXX=libc++
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Release
        - LIBCXX=libc++
    # GCC on OSX is just a wrapper for Clang.

install:
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade conan --ignore-installed
  - conan user
  - conan --version
  - conan remote add autocheck https://api.bintray.com/conan/thejohnfreeman/autocheck
  - conan remote list

script:
  - mkdir build
  - cd build
  - conan install
    --setting "compiler.libcxx=$LIBCXX"
    --setting "build_type=$BUILD_TYPE"
    --build missing
    ..
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - cmake --build . --config ${BUILD_TYPE} -- -j 4
  - ctest -C $BUILD_TYPE -V
